channels:
- conda-forge
dependencies:
- jupyterlab
- mpltern =1.0.4
- calphy =1.3.8
- nbgitpuller =1.2.1
- pyiron_base =0.8.4
- pyiron_atomistics =0.6.0
- pyiron_snippets =0.1.1
- pyiron_contrib =0.1.16
- pyiron_potentialfit =0.3.2
- pyiron_workflow =0.9.0
- pyiron_gui =0.0.12
- mlip =2.0
- sqsgenerator =0.3
- pyxtal =0.6.7
- structdbrest =0.0.1
- psycopg2 =2.9.9
- netCDF4 =1.6.5
- numba =0.59.0
- jupyter-server-proxy =4.1.2
